### ISSUE TITLE
Logo invertido

### ISSUE THREAD

**Issue by adrianorcampos** [frente-uff/face-shield#1]
Fala pessoal...
Parabéns pelo trabalho!!!!

FRONT-UFF_Projeto_FaceShield-UFF-LAMMOC_v5.0_FINAL.stl
Nesse arquivo, ao que parece através do visualizador do GitHub, o logo do projeto está de cabeça para baixo...

**Comment by lucasgetirana** [comment]
Opa, valeu pela dica, Adriano! O logo é invertido porque a peça é utilizada na orientação do logo da UFF! O que mantivemos invertido é o logo da Prusa, que no .stl parece na orientação correta, que é do projeto original e mantivemos por respeito aos desenvolvedores!

**Comment by adrianorcampos** [comment]
Por nada!
Legal o respeito aos caras... Curti mais ainda!!!
